### ISSUE TITLE
Time conversion uses undefined data

### ISSUE THREAD

**Issue by MSFT-Chris-Barrett** [PlayFab/XPlatCoreTemplate#51]
https://github.com/PlayFab/XPlatCoreTemplate/blob/69355e81f7f8328a0132dde8cdd5580149abecc9/source/code/include/playfab/PlayFabPlatformUtils.h#L59

After `std::get_time()`, `timeStruct` needs to have its `tm_isdst` set.  Please see documentation on `std::get_time()`, such as the line _Note: tm_isdst is not written to, and needs to be set explicitly for use with functions such as mktime_ from https://en.cppreference.com/w/cpp/io/manip/get_time

`std::get_time()` leaves the value of `tm_isdst` unaltered, which means that it's _**undefined**_ in this code as it's written now.  Depending on whether that value is negative, zero, or positive, one of three different behaviors of `mktime()`/`_mkgmtime()` will occur.  `timegm()` doesn't care, as it ignores `tm_isdst`.

Also see this documentation on the Windows-only `_mkgmtime()`, which describes it following similar behavior: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/mkgmtime-mkgmtime32-mkgmtime64?view=vs-2019

(Originally reported here: https://github.com/PlayFab/XPlatCppSdk/issues/34 .  Moved to this repo since it belongs here instead of in the generated code.  Merged explanation from PR so all information's in one place.)

**Comment by toddbellMSFT** [comment]
https://github.com/PlayFab/XPlatCoreTemplate/commit/d23b1ca0643edde6a9430f051c6b4aff996208fc Fixed with this commit.
