### ISSUE TITLE
Intermittent crash in ExecuteRequest during shutdown

### ISSUE THREAD

**Issue by MSFT-Chris-Barrett** [PlayFab/XPlatCoreTemplate#79]
One of our top iOS crashes looks to be in block execution within ExecuteRequest().  So far I've managed to repro it only once in a debugger, and it was this line due to `body` being nil: https://github.com/PlayFab/XPlatCoreTemplate/blob/ded594258c367d3e92909f951d826854f3a4dfab/source/code/source/playfab/PlayFabIOSHttpPlugin.mm#L271

All parameters given when calling the block were nil: `data`, `response`, and `error`.  This crash occurs _sometimes_ when a user is closing our app or it's otherwise exiting.  In the one case I repro'd, it was from dismissing/swiping-up the app from the overview of running apps.

Current guess is toward the app exiting while a request is completing.  So _something somewhere_ is destroyed, then this completionHandler block is run.  I'm still learning Objective-C for the first time to look into this, so I'm not yet familiar with what-all cases to watch out for in how relevant memory-is/objects-are being handled.

**Comment by pgilmorepf** [comment]
Thanks for reporting this, I'll file the issue with the team.

**Comment by toddbellMSFT** [comment]
This issue has been addressed with the latest commit: 

https://github.com/PlayFab/XPlatCoreTemplate/commit/93e00bec4ec9cbf75ff0f35e630b4d09a3dade02 

Please let us know if you continue to see this issue after the next release.
